description: Un blog perso pour partager idées et expériences sur le comment "faire avec" pour "être libres ensemble". Community building - facilitation - communautés ouvertes contributives - dynamiques des groupes - inclusion et ouverture - biens communs
url: http://qrohlf.com
permalink: /posts/:title
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
future: true
poole:
    word_separator: "-"
include: [".well-known"]
sass:
    sass_dir: _sass
    sourcemap: true
